image: gitpod/workspace-node
tasks:
  - init: echo 'docker' # runs during prebuild
  - command: docker compose up -d

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 80
    onOpen: open-browser

  - port: 3306
    onOpen: open-browser

vscode:
 extensions:
  - dbaeumer.vscode-eslint
  
  - ms-azuretools.vscode-docker